name: '\U00002728 Feature Request'
description: Request a new feature
labels: [feature request]
body:
  - type: markdown
    attributes:
        value: |
            Thank you for taking the time to request a new feature!
  - type: textarea
    id: problem
    attributes:
        label: Describe the problem
        description: Please provide a clear and concise description of the problem this feature would solve. The more information you can provide here, the better.
        placeholder: I'm always frustrated when...
    validations:
        required: true
  - type: textarea
    id: solution
    attributes:
        label: Describe the proposed solution
        description: Please provide a clear and concise description of what you would like to happen.
        placeholder: I would like to see...
    validations:
        required: true
