export const keyMap = {
    cmd: '⌘',
    shift: '⇧',
    ctrl: '⌃',
    option: '⌥',
    enter: '↵',
    del: '⌫',
    esc: '⎋',
    tab: '⇥',
    capslock: '⇪',
    up: '↑',
    down: '↓',
    left: '←',
    right: '→',
    pageup: '⇞',
    pagedown: '⇟',
    home: '↖',
    end: '↘',
    help: '?',
    space: '␣'
}
